title: **汪斌**
# tagline: 
description: 东南大学社会学系讲师
# Comment out url when working locally to resolve base urls correctly
url: https://bwPhD.github.io

# Owner/author information
owner:
  name: 汪斌
  avatar: 1.png
  bio: 汪斌 东南大学社会学系讲师 
  email: wangbinseu@edu.com.cn
  organization: https://rwxy.seu.edu.cn/2023/0912/c8792a464254/pagem.htm
  # cv: x.pdf
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # twitter: lancecai2002
  # github: GuangLun2000
  # linkedin: hanlincai
  # bilibili: 594030035
  # researchgate: https://www.researchgate.net/profile/Hanlin-Cai
  # zhihu: https://www.zhihu.com/people/chlire
  # facebook: caihanlin2002
  # instagram: lancecai2002
  # lastfm:
  # tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
# google_verify: ""

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: 成果
    url: /publications/
  - title: 荣誉
    url: /awards/
  - title: 教学
    url: /teach/
  - title: 招生
    url: /blogs/
  # - title: Startups
    # url: /startups/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: 南京，中国
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class

# disqus settings:
disqus:
  shortname: lancecai

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

# Latest update in 2024/02/07 by Bin Wang

# 以下为新增加的配色部分
theme_colors:
  light:
    # Primary
    primary: "#bf874b"

    # Menu
    menu_primary: "#264A33"
    menu_text: "#fff"
    menu_text_active: "#bf874b"
    menu_title: "#bf874b"

    # Home sections
    home_section_odd: "#fff"
    home_section_even: "#F8F5F2"

    link: "#ad5d07"
    link_hover: "#264A33"

  dark:
    # Primary
    primary: "#F3B26D"
    # text: "#8342a8"
    # link_decoration: "underline"

    menu_primary: "#0E182E"
    menu_text_active: "#F3B26D"

    background: "#1C2945"

    # Home sections
    home_section_odd: "#1C2945"
    home_section_even: "#0E182E"

    link: "#F3B26D"
    link_hover: "#377DE8"
